Refactor S02setup to check if /boot is already mounted before mounting, and add S03upgrade-monitor script to check for updates on USB drives

diff --git a/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup b/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup
--- a/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup
+++ b/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup
@@ -2,9 +2,11 @@
 
 case "$1" in
 	start)
-		echo -n "Mount boot: "
-		mount /dev/mmcblk0p1 /boot
-		[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+		if ! mountpoint -q /boot; then
+			echo -n "Mount boot: "
+			mount /dev/mmcblk0p1 /boot
+			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+		fi
 
 		# Permit rootfs updates using update.tar.gz
 		if [ -f /boot/update.tar.gz ]; then
