Improved first-setup script
Documented files needed for initial setup
SSH does not accept empty passwords any more
Improved update script (WIP)

diff --git a/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup b/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup
--- a/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup
+++ b/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S02setup
@@ -2,39 +2,82 @@
 
 case "$1" in
 	start)
-		if ! mountpoint -q /boot; then
-			echo -n "Mount boot: "
-			mount /dev/mmcblk0p1 /boot
+		# Apply WiFi config options
+		if [ -f /boot/dhcpcd.conf ]; then
+			echo -n "Found dhcpcd.conf on /boot, moving... "
+			mv /boot/dhcpcd.conf /etc/dhcpcd.conf
+			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+		fi
+		if [ -f /boot/wpa_supplicant.conf ]; then
+			echo -n "Found wpa_supplicant.conf on /boot, moving... "
+			mv /boot/wpa_supplicant.conf /etc/wpa_supplicant.conf
 			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
 		fi
 
-		# Permit rootfs updates using update.tar.gz
-		if [ -f /boot/update.tar.gz ]; then
-			if [ -f /pre-update ]; then
-				/pre-update
-				rm /pre-update
+		# Change root password via /boot/password(.txt)
+		PW_FILE=""
+		if [ -f /boot/password ]; then
+			PW_FILE="/boot/password"
+		elif [ -f /boot/password.txt ]; then
+			PW_FILE="/boot/password.txt"
+		fi
+
+		if [ ! -z "$PW_FILE" ]; then
+			PW=`cat $PW_FILE`
+			if [ -z "$PW" ]; then
+				echo "Cannot update root password because it is empty!"
+			else
+				echo -n "Changing root password... "
+
+				# Change root password
+				echo -e "$PW\n$PW" | passwd &> /dev/null
+
+				# Overwrite password file with zeros and then delete it
+				echo "$PW" | tr '[:print:][:space:]' '0' > $PW_FILE
+				rm -f $PW_FILE
+
+				[ $? -eq 0 ] && echo "OK" || echo "ERROR"
 			fi
-
-			gunzip /boot/update.tar.gz -c | tar -xvC / && rm /boot/update.tar.gz
-
-			if [ -f /post-update ]; then
-			   /post-update
-			   rm /post-update
-			fi
 		fi
 
-		# Move system files if requested
-		if [ -f /boot/dhcpcd.conf ]; then
-			mv /boot/dhcpcd.conf
-		fi
-		if [ -f /boot/wpa_supplicant.conf ]; then
-			mv /boot/wpa_supplicant.conf /etc/wpa_supplicant.conf
+		# Install SSH keys via /boot/authorized_keys
+		if [ -f /boot/authorized_keys ]; then
+			echo -n "Installing SSH keys... "
+
+			# Install certificate and adjust permissions
+			mkdir -p /root/.ssh
+			cp /boot/authorized_keys /root/.ssh/authorized_keys
+			chmod 600 /root/.ssh/authorized_keys
+
+			# Overwrite certificate with zeros and then delete it
+			KEY=`cat /boot/authorized_keys`
+			echo "$KEY" | tr '[:print:][:space:]' '0' > /boot/authorized_keys
+			rm -f /boot/authorized_keys
+
+			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
 		fi
 
-		# Enable SSH on demand
+		# Enable ADB if requested
+		if [ -f /boot/adb ]; then
+			echo -n "Enabling ADB... "
+			mv /etc/init.d/30adbd /etc/init.d/S30adbd
+			/etc/init.d/S30adbd start
+			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+		fi
+
+		# Enable SSH if requested
 		if [ -f /boot/ssh ] && [ ! -f /etc/init.d/S50dropbear ]; then
+			echo -n "Enabling SSH... "
 			mv /etc/init.d/50dropbear /etc/init.d/S50dropbear
 			/etc/init.d/S50dropbear start
+			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+		fi
+
+		# Disable this service again if needed
+		if [ -f /etc/init.d/S02setup ]; then
+			echo -n "Disabling auto-setup service... "
+			mv /etc/init.d/S02setup /etc/init.d/02setup
+			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
 		fi
 
 		;;
