fix: add restart function to rootfs-upgrade to prevent multiple instances of it running when DuetScreen updates itself

diff --git a/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S50rootfs-upgrade b/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S50rootfs-upgrade
--- a/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S50rootfs-upgrade
+++ b/board/duet3d/duetscreen/rootfs_overlay/etc/init.d/S50rootfs-upgrade
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 UPGRADE_FILE="update.tar.gz"
+PIDFILE="/var/run/S50rootfs-upgrade.pid"
 
 function do_upgrade() {
 	FILE="$1"
@@ -9,6 +10,7 @@ function do_upgrade() {
 	gunzip -c $FILE | tar -xvC / pre-update &> /dev/null || true
 	if [ -f /pre-update ]; then
 		chmod +x /pre-update
+		echo "Running pre-update script..."
 		/pre-update $FILE
 	fi
 
@@ -19,39 +21,60 @@ function do_upgrade() {
 	# Run post-update if applicable
 	if [ -f /post-update ]; then
 		chmod +x /post-update
+		echo "Running post-update script..."
 		/post-update
 		rm /post-update
 	fi
 }
 
+start() {
+	# Check for update file in /boot and install it if present
+	if [ -f "/boot/$UPGRADE_FILE" ]; then
+		echo "Found $UPGRADE_FILE on /boot, installing... "
+		do_upgrade "/boot/$UPGRADE_FILE"
+		[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+	fi
+
+	# Keep checking for updates on USB drives
+	while true; do
+		for MOUNT_POINT in $(echo /media/usb[0-7] 2>/dev/null); do
+			if mountpoint -q "$MOUNT_POINT"; then
+				if [ -f "$MOUNT_POINT/$UPGRADE_FILE" ]; then
+		echo "Found $UPGRADE_FILE on $MOUNT_POINT, installing... "
+					do_upgrade "$MOUNT_POINT/$UPGRADE_FILE"
+					[ $? -eq 0 ] && echo "OK" || echo "ERROR"
+				fi
+			fi
+		done
+		sleep 2
+	done &
+	echo $! > "$PIDFILE"
+}
+
+stop() {
+	if [ -f "$PIDFILE" ]; then
+		kill $(cat "$PIDFILE")
+		rm -f "$PIDFILE"
+	fi
+}
+
+restart() {
+	stop
+	start
+}
+
 case "$1" in
 	start)
-		# Check for update file in /boot and install it if present
-		if [ -f "/boot/$UPGRADE_FILE" ]; then
-			echo -n "Found $UPGRADE_FILE on /boot, installing... "
-			do_upgrade "/boot/$UPGRADE_FILE" 
-			[ $? -eq 0 ] && echo "OK" || echo "ERROR"
-		fi
-
-		# Keep checking for updates on USB drives 
-		while true; do
-			for MOUNT_POINT in $(echo /media/usb[0-7] 2>/dev/null); do
-				if mountpoint -q "$MOUNT_POINT"; then
-					if [ -f "$MOUNT_POINT/$UPGRADE_FILE" ]; then
-                        echo -n "Found $UPGRADE_FILE on $MOUNT_POINT, installing... "
-						do_upgrade "$MOUNT_POINT/$UPGRADE_FILE"
-						[ $? -eq 0 ] && echo "OK" || echo "ERROR"
-					fi
-				fi
-			done
-			sleep 2
-		done &
+		start
 		;;
 	stop)
-		killall S03rootfs-upgrade
+		stop
+		;;
+	restart)
+		restart
 		;;
 	*)
-		echo "Usage: $0 start" >&2
+		echo "Usage: $0 {start|stop|restart}" >&2
 		exit 1
 		;;
 esac
