Generate NAND update ZIP automatically
Removed nand_factory_reset script from image and moved it to update pkg

diff --git a/board/duet3d/duetscreen/bin/post-update b/board/duet3d/duetscreen/bin/post-update
--- a/board/duet3d/duetscreen/bin/post-update
+++ b/board/duet3d/duetscreen/bin/post-update
@@ -1,16 +1,25 @@
 #!/bin/sh
 
-# Blank the screen first
-# FIXME: Use ffmpeg to write an almost black image. Without this the display freezes and fades away
+# Stop DuetScreen first
+/etc/init.d/S21DuetScreenMonitor stop
+
+# Blank the screen first and use ffmpeg to write an almost black image. Without this the display freezes and fades away
 echo 0 > /sys/class/vtconsole/vtcon1/bind
 ffmpeg -loglevel quiet -f lavfi -i color=0x010101:s=1024x600 -f rawvideo -pix_fmt bgra -y /dev/fb0
 echo 1 > /sys/class/vtconsole/vtcon1/bind
 echo -ne '\033c' > /dev/tty1
 
 # Begin NAND factory reset
-echo 'NAND Factory Reset' > /dev/tty1
+echo "NAND Flash Update" > /dev/tty1
 echo > /dev/tty1
 
+# Check if rootfs.ubi exists
+if [ ! -f rootfs.ubi ]; then
+    echo "Error: rootfs.ubi not found!" > /dev/tty1
+    exit 1
+fi
+
+# Erase Flash
 echo "Erasing NAND flash..." > /dev/tty1
 flash_erase /dev/mtd0 0 0 > /dev/null
 flash_erase /dev/mtd1 0 0 > /dev/null
@@ -18,6 +27,7 @@ flash_erase /dev/mtd2 0 0 > /dev/null
 flash_erase /dev/mtd3 0 0 > /dev/null
 # mtd4 is erased by ubiformat
 
+# Write Flash
 echo "Flashing awboot..." > /dev/tty1
 nandwrite -p /dev/mtd0 awboot-boot-spi.bin > /dev/null
 echo "Flashing dtb..." > /dev/tty1
@@ -29,4 +39,12 @@ nandwrite -p /dev/mtd3 zImage > /dev/null
 echo "Flashing ubi..." > /dev/tty1
 ubiformat /dev/mtd4 --flash-image=rootfs.ubi > /dev/tty1
 
+# Done
 echo "Done!" > /dev/tty1
+
+# Clean up again
+rm -f awboot-boot-spi.bin sun8i-duet3d-duetscreen-linux.dtb optee.bin zImage rootfs.ubi post-update
+
+# Wait a moment and then restart DuetScreen
+sleep 10
+/etc/init.d/S21DuetScreenMonitor start
